service: aws-nodejs-chatbot-api

frameworkVersion: "3"
useDotenv: true

custom:
  bucketName: ${env:AWS_S3_BUCKET_NAME}

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
  - Effect: Allow
    Action:
      - s3:*
    Resource: "arn:aws:s3:::${self:custom.bucketName}/*"

functions:
  chat:
    handler: handler.chat
    events:
      - http:
          path: chat
          method: post
          cors: true
    environment:
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
      AWS_S3_BUCKET_NAME: ${env:AWS_S3_BUCKET_NAME}
      AWS_ROOT_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
      AWS_ROOT_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    timeout: 120    

plugins:
  - serverless-offline
  - serverless-plugin-typescript 
