service: aws-python-flask-api

frameworkVersion: '3'
useDotenv: true

package:
  exclude:
    - node_modules/**
    - venv/**

custom:
  wsgi:
    app: app.app
    pythonBin: python3
  pythonRequirements:
    zip: true
    slim: true

provider:
  name: aws
  runtime: python3.9
  region: ${env:AWS_REGION}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    environment:
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
      AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}

plugins:
  - serverless-wsgi
  - serverless-python-requirements
