service: aws-python-chatbot-api

frameworkVersion: '3'
useDotenv: true

package:
  exclude:
    - node_modules/**
    - venv/**

custom:
  wsgi:
    app: app.app
    pythonBin: python3
  pythonRequirements:
    zip: true
    slim: true
  bucketName: ${env:AWS_S3_BUCKET_NAME}
  lambdaRoleArn: arn:aws:iam::${AWS::AccountId}:role/aws-python-chatbot-api-${sls:stage}-${env:AWS_REGION}-lambdaRole

provider:
  name: aws
  runtime: python3.9
  region: ${env:AWS_REGION}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    environment:
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}

resources:
  Resources:
    ChatbotBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.bucketName}
    ChatbotBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ChatbotBucket
        PolicyDocument:
          Statement:
            - Action:
                - s3:GetObject
              Effect: Allow
              Principal: "*"
              Resource: !Sub arn:aws:s3:::${ChatbotBucket}/*
            - Action:
                - s3:PutObject
              Effect: Allow
              Principal:
                AWS:
                  - !Sub ${self:custom.lambdaRoleArn}
              Resource: !Sub arn:aws:s3:::${ChatbotBucket}/*

plugins:
  - serverless-wsgi
  - serverless-python-requirements
