name: Tests, Static Analysis and Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "**"

  push:
    branches:
      - "main"

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3  
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm run test:ci

      - name: Build
        run: pnpm run build

  ui-deployment:
    runs-on: ubuntu-latest
    needs:
      - integration
    if: always() && needs.integration.result == 'success'
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          env="preview"
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            env="production"
          fi
          cd packages/ui && vercel pull --yes --environment=$env --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          args=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            args="--prod"
          fi
          cd packages/ui && vercel deploy $args --token=${{ secrets.VERCEL_TOKEN }}

  api-deployment:
    runs-on: ubuntu-latest
    needs:
      - integration
    if: always() && needs.integration.result == 'success'
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm and modules
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Install serverless globally
        run: pnpm add serverless --global

      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy API
        run: pnpm --filter api run deploy